# -----------------------------------
slave:
  topic_input_velocity: "/mobile_base_controller/cmd_vel"
  topic_output_velocity: "/mobile_base_controller/cmd_vel"
  topic_input_odometry: "/mobile_base_controller/odom_comb"
  topic_output_satet: "/state"
  controller_type: 1                       #1: pseudo inverse 2: lypanov