# -----------------------------------
formation:

  names: ["robot_master","robot1","robot2"]
  
  robot_master:
    pose: [0 , 0 , 0, 0]

  robot1:
    pose: [-1.5 , 1.5 , 0, 0]

  robot2:
    pose: [-1.5 , -1.5 , 0, 0]


robot1:

  publish_tf: true

  world_frame:  "/map" #global frame. Has to be the same for hole correspiondent formation

  topic_current_odometry:     "odometry/filtered"  #topic the current odometry of the robot is published at

  topic_target_odometry:      "/robot_master/odometry/filtered" #topi  the target odometry of the robot is published at

  controller_type: 2                            # 1-> pseudo_invers 2->lyapov 3->angl_dist


robot2:

  publish_tf: true

  world_frame: "/map"

  topic_current_odometry:     "odometry/filtered"

  topic_target_odometry:      "/robot_master/odometry/filtered"
  
  controller_type: 2                             # 1-> pseudo_invers 2->lyapov 3->angl_dist
  
robot_master:

  publish_tf: true

  world_frame: "/map"

  topic_current_odometry:     "odometry/filtered"

  topic_target_odometry:      "/trajectory_odom"

  controller_type: 2                            # 1-> pseudo_invers 2->lyapov 3->angl_dist


algorithm:

  lyapunov: [2.0,10.0,2.0]               # parameter for lyapunov algorythm: kx,kphi,vd,omegad
  

planner: 

  type: 0         #0->lissajous 
  pause: true
  iterations: 10
  
  growth: 0.33 
  r0: 3

  omega: 0.03
  ratio: 2
  phaseshift: 0.0
  amplifier_x: 3.0
  amplifier_y: 3.0
