# -----------------------------------
planner: 
  type: 0        #0->lissajous 1->circle 2->clickedPose 3->spiral 4->StepResponse
  pause: false
  iterations: 1
  reference:  [0.75 , 0 , 0, 0 ,0 ,0 ]    #X Y Z R P Y
  
  growth: 0.33 
  r0: 3

  omega: 0.03
  ratio: 2
  phaseshift: 0.0
  amplifier_x: 3.0
  amplifier_y: 3.0

  step_sizes: [1.0, 1.0, 0.5]  # x [m] y[m] phi[times pi] -> [1.0 1.0 0.5] means 1m in x 1m in y and 0.5pi in phi
  delay: 6.0


formation:
  names: ["master","robot1","robot2","robot3","robot4","robot5"] #Names of the robots belonging to one formation
  # names: ["master"]


  # Remaped, shared parameter for all the robots
controller_type: 2                            # 1-> pseudo_invers 2->lyapov 3->angl_dist
lyapunov: [7.0,12.0,2.0]               # parameter for lyapunov algorythm: kx,kphi,vd,omegad
angle_distance: [7.0,5.0,0.3]   # parameter for angle distance algorythm: kl,kpsi,d  
topic_current_odometry: "base_pose_ground_truth"  #Source of state estamination
publish_tf: true  #Should be published at tf?
world_frame: "/map" #Name of the map frame
thresh: [0.0, 0.0, 0.0]


#Formation member specification
master:      
  controller: 
    controller_type: 2
    reference: [0.75 , 0 , 0, 0 ,0 ,0 ]    #X Y Z R P Y    
    topic_target_odometry:      "/trajectory_odom"

robot1:  
  controller:
    master: "master"
    reference: [1.25 , -1.25, 0, 0 ,0 ,0 ]    #X Y Z R P Y
    topic_target_odometry:    "/master/base_pose_ground_truth"   

robot2:      
  controller:
    master: "master"
    reference: [1.25 , 1.25, 0, 0 ,0 ,0 ]    #X Y Z R P Y
    topic_target_odometry:       "/master/base_pose_ground_truth" #topi  the target odometry of the robot is published at

robot3:
  controller:
    master: "master"
    reference: [-1.5,1.25, 0, 0 ,0 ,0 ]    #X Y Z R P Y
    topic_target_odometry:      "/master/base_pose_ground_truth" #topi  the target odometry of the robot is published at

robot4:  
  controller:
    master: "master"
    reference: [-1.5, -1.25, 0, 0 ,0 ,0 ]    #X Y Z R P Y
    topic_target_odometry:    "/master/base_pose_ground_truth"     

robot5:
  controller:
    master: "master"
    reference: [-0.75 , 0 , 0, 0 ,0 ,0 ]    #X Y Z R P Y
    publish_tf: true  
    topic_target_odometry:       "/master/base_pose_ground_truth" #topi  the target odometry of the robot is published at