# -----------------------------------
#Input topic have to be decalred gloabelly while output topics are defined relative to the robots namespace
robot1:
  topic_input_velocity: "/robot_master/mobile_base_controller/cmd_vel"
  topic_output_velocity: "mobile_base_controller/cmd_vel"
  topic_input_odometry: "mobile_base_controller/odom"
  topic_output_state: "state"



robot2:
  topic_input_velocity: "/robot_master/mobile_base_controller/cmd_vel"
  topic_output_velocity: "mobile_base_controller/cmd_vel"    

  topic_input_odometry: "mobile_base_controller/odom"
  topic_output_state: "state"



robot_master:
  topic_input_velocity: "/key_vel"
  topic_output_velocity: "mobile_base_controller/cmd_vel"

  topic_input_odometry: "mobile_base_controller/odom"
  topic_output_state: "state"





