# -----------------------------------
robot1:
  world_frame: "/map"

  topic_current_odometry:  "mobile_base_controller/odom"

  topic_target_odometry: "/trajectory_odom"

  controller_type: 2                            # 1-> pseudo_invers 2->lyapov 3->angl_dist




robot2:
  world_frame: "/map"

  topic_current_odometry:   "mobile_base_controller/odom"

  topic_target_odometry: "/trajectory_odom"
  
  controller_type: 2                             # 1-> pseudo_invers 2->lyapov 3->angl_dist



robot_master:
  world_frame: "/map"

  topic_current_odometry: "mobile_base_controller/odom"

  topic_target_odometry: "/trajectory_odom"

  controller_type: 2                            # 1-> pseudo_invers 2->lyapov 3->angl_dist


algorithm:
  lyapunov: [7.0,7.0,11.0]               # parameter for lyapunov algorythm: kx,kphi,vd,omegad
  