# -----------------------------------
robot1:
  world_frame: "/map"

  topic_input_velocity: "/robot_master/mobile_base_controller/cmd_vel"
  topic_output_velocity: "mobile_base_controller/cmd_vel"

  topic_input_odometry: "mobile_base_controller/odom"
  topic_output_state: "state"

  topic_output_control_dif: "control_diff"

  coord: [-1.25,1.25,0.0]

  controller_type: 1                            # 1-> pseudo_invers 2->lyapov




robot2:
  world_frame: "/map"

  topic_input_velocity: "/robot_master/mobile_base_controller/cmd_vel"
  topic_output_velocity: "mobile_base_controller/cmd_vel"    

  topic_input_odometry: "mobile_base_controller/odom"
  topic_output_state: "state"

  topic_output_control_dif: "control_diff"
  
  coord: [-1.25,-1.25,0.0]

  controller_type: 1                            # 1-> pseudo_invers 2->lyapov



robot_master:
  world_frame: "/map"

  topic_input_velocity: "/key_vel"
  topic_output_velocity: "mobile_base_controller/cmd_vel"

  topic_input_odometry: "mobile_base_controller/odom"
  topic_input_state: "/move_base_simple/goal"

  coord: [0.0,0.0,0.0]

  controller_type: 2                            # 1-> pseudo_invers 2->lyapov


