name: "Slave1"
topic_input_velocity: "/mobile_base_controller/cmd_vel"
topic_output_velocity: "/mobile_base_controller/cmd_vel"
topic_controller_type: 0				#!0: pseudo inverse 1: lypanov
reference: [0 , 0 , 0]

