# -----------------------------------
robot1:
  world_frame: "/map"

  topic_input_odometry:  "base_pose_ground_truth"

  #topic_target_velocity: "/robot_master/mobile_base_controller/cmd_vel"   

  #topic_target_state:  "/robot_master/state"

  topic_target_odometry: "/robot_master/base_pose_ground_truth"
  


  controller_type: 2                           # 1-> pseudo_invers 2->lyapov 3->angl_dist




robot2:
  world_frame: "/map"

  topic_input_odometry:  "base_pose_ground_truth"

  #topic_target_velocity: "/robot_master/mobile_base_controller/cmd_vel"  

  #topic_target_state:  "/robot_master/state"

  topic_target_odometry: "/robot_master/base_pose_ground_truth"

  

  controller_type: 2                             # 1-> pseudo_invers 2->lyapov 3->angl_dist



robot_master:
  world_frame: "/map"

  topic_input_odometry: "base_pose_ground_truth"

  #topic_target_velocity: "/key_vel"
  
  #topic_target_state: "/trajectory"

  topic_target_odometry: "/trajectory_odom"


  controller_type: 2                        # 1-> pseudo_invers 2->lyapov 3->angl_dist


