# -----------------------------------
robot1:
  world_frame: "/map"

  topic_input_odometry: "mobile_base_controller/odom"

  topic_target_velocity: "/robot_master/mobile_base_controller/cmd_vel"   

  topic_target_state:  "/robot_master/state"
  

  coord: [-1.25,1.25,0.0]

  controller_type: 3                            # 1-> pseudo_invers 2->lyapov




robot2:
  world_frame: "/map"

  topic_input_odometry:  "mobile_base_controller/odom"

  topic_target_velocity: "/robot_master/mobile_base_controller/cmd_vel"  

  topic_target_state: "/robot_master/state" 
  

  coord: [-1.25,-1.25,0.0]

  controller_type: 3                            # 1-> pseudo_invers 2->lyapov




robot_master:
  world_frame: "/map"

  topic_input_odometry: "mobile_base_controller/odom"

  topic_target_velocity: "/key_vel"
  
  topic_target_state: "/move_base_simple/goal"
  

  coord: [0.0,0.0,0.0]

  controller_type: 3                          # 1-> pseudo_invers 2->lyapov


