# -----------------------------------
# formation:
#   names: ["robot_master","robot1","robot2","robot3"]
  
#   robot_master:
#     pose: [0 , 0 , 0, 0]

#   robot1:
#     pose: [2 , 2 , 0, 0]

#   robot2:
#     pose: [-2 , -2 , 0, 0]


robot1:
  world_frame: "/map" #global frame. Has to be the same for hole correspiondent formation

  topic_current_odometry:  "odometry/filtered"  #topic the current odometry of the robot is published at

  topic_target_odometry: "/trajectory_odom" #topi  the target odometry of the robot is published at

  controller_type: 2                            # 1-> pseudo_invers 2->lyapov 3->angl_dist

  lyapunov: [7.0,7.0,11.0]



robot2:
  world_frame: "/map"

  topic_current_odometry:   "odometry/filtered"

  topic_target_odometry: "/trajectory_odom"
  
  controller_type: 2                             # 1-> pseudo_invers 2->lyapov 3->angl_dist

  lyapunov: [7.0,7.0,11.0]

robot3:
  world_frame: "/map"

  topic_current_odometry:   "odometry/filtered"

  topic_target_odometry: "/trajectory_odom"
  
  controller_type: 2                             # 1-> pseudo_invers 2->lyapov 3->angl_dist

  lyapunov: [7.0,7.0,11.0]


robot_master:
  world_frame: "/map"

  topic_current_odometry: "odometry/filtered"

  topic_target_odometry: "/trajectory_odom"

  controller_type: 2                            # 1-> pseudo_invers 2->lyapov 3->angl_dist

  lyapunov: [7.0,7.0,11.0]               # parameter for lyapunov algorythm: kx,kphi,vd,omegad
  

planner: 
  type: 0         #0->lissajous planner 
  pause: false
  iterations: 10
  omega: 0.05
  ratio: 1
  phaseshift: 1.57079632679
  amplifier_x: 5.0
  amplifier_y: 5.0