# -----------------------------------
topic_input_velocity: "/key_vel"
topic_output_velocity: "/mobile_base_controller/cmd_vel"
topic_input_odometry: "/mobile_base_controller/odom_comb"
topic_output_satet: "/state"
